PcSantos.UI.Web/Controllers/ClienteController.cs
using PcSantos.ApplicationServices;
using PcSantos.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PcSantos.UI.Web.Controllers
{
    public class ClienteController : Controller
    {
        IClienteAppServices clienteApp;

        public ClienteController(IClienteAppServices clienteAppInstance)
        {
            this.clienteApp = clienteAppInstance;
        }

        public ActionResult LogOff()
        {
            AppHelper.LogOff();

            return RedirectToAction("Inicio", "WebApp");
        }
        
        [AllowAnonymous]
        public ActionResult Login()
        {
            var clienteLoginViewModel = new ClienteLoginViewModel();
            return View(clienteLoginViewModel);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(ClienteLoginViewModel clienteLoginViewModel)
        {
            //string senha = clienteApp.CriarHash(clienteLoginViewModel.Senha);
            Cliente cliente = clienteApp.ObterPorEmailSenha(clienteLoginViewModel.Email, clienteLoginViewModel.Senha);

            if (cliente == null)
            {
                clienteLoginViewModel.Mensagem = "Cliente não encontrado";
                return RedirectToAction("Login");
            }
            else
            {
                AppHelper.RegistrarCliente(cliente);
                return RedirectToAction("Inicio", "WebApp");
            }            
        }

        [AllowAnonymous]
        public ActionResult Registro()
        {
            var cliente = new ClienteRegistroViewModel();
            return View(cliente);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Registro(ClienteRegistroViewModel clienteRegistro)
        {
            if (string.IsNullOrEmpty(clienteRegistro.Email))
            {
                ModelState.AddModelError("Email", "O email deve ser informado");
            }

            if (string.IsNullOrEmpty(clienteRegistro.Senha))
            {
                ModelState.AddModelError("Senha", "O email deve ser informado");
            }
            else
            {
                if (clienteRegistro.Senha != clienteRegistro.ConfirmarSenha)
                {
                    ModelState.AddModelError("ConfirmarSenha", "A confirmação deve ser igual a senha");
                }
            }            

            if(ModelState.IsValid)
            {
                var cliente = new Cliente();

                cliente.Id = Guid.NewGuid().ToString();
                cliente.Nome = clienteRegistro.Nome;
                cliente.Email = clienteRegistro.Email;
                cliente.Senha = clienteRegistro.Senha;
                cliente.CPF = clienteRegistro.CPF;
                cliente.DataNasc = clienteRegistro.DataNasc;
                cliente.Sexo = clienteRegistro.Sexo;
                cliente.Telefone = clienteRegistro.Telefone;
                cliente.CEP = clienteRegistro.CEP;
                cliente.Endereco = clienteRegistro.Endereco;
                cliente.Numero = clienteRegistro.Numero;
                cliente.Bairro = clienteRegistro.Bairro;
                cliente.Cidade = clienteRegistro.Cidade;
                cliente.Estado = clienteRegistro.Estado;                

                clienteApp.Incluir(cliente);

                AppHelper.RegistrarCliente(cliente);
                return RedirectToAction("Inicio", "WebApp");
            }  
            return View(clienteRegistro);
        }

        [Authorize]
        public ActionResult DashboardCliente()
        {
            var cliente = AppHelper.ObterClienteLogado();

            if (cliente == null)
            {
                return RedirectToAction("Login");
            }

            return View(cliente);
        }

        [Authorize]
        public ActionResult DadosPessoais(string id)
        {            
            var cliente = clienteApp.ObterPorId(id);

            var clienteDadosPessoais = new ClienteDadosPessoaisViewModel()
            {
                Id = cliente.Id,
                Nome = cliente.Nome,
                Email = cliente.Email,
                Senha = cliente.Senha,
                CPF = cliente.CPF,
                DataNasc = cliente.DataNasc,
                Sexo = cliente.Sexo,
                Telefone = cliente.Telefone
            };  

            return View(clienteDadosPessoais);
        }

        [Authorize]
        [HttpPost]
        public ActionResult DadosPessoais(ClienteDadosPessoaisViewModel dadosPessoais)
        {
            try
            {

                var cliente = clienteApp.ObterPorId(dadosPessoais.Id);

                var clienteAlterar = new Cliente()
                {
                    Id = cliente.Id,
                    Nome = dadosPessoais.Nome,
                    Email = dadosPessoais.Email,
                    Senha = dadosPessoais.Senha,
                    CPF = dadosPessoais.CPF,
                    DataNasc = dadosPessoais.DataNasc,
                    Sexo = dadosPessoais.Sexo,
                    Telefone = dadosPessoais.Telefone,
                    CEP = cliente.CEP,
                    Endereco = cliente.Endereco,
                    Numero = cliente.Numero,
                    Bairro = cliente.Bairro,
                    Cidade = cliente.Cidade,
                    Estado = cliente.Estado
                };

                clienteApp.Alterar(clienteAlterar);

                return RedirectToAction("DashboardCliente");
            }
            catch
            {
                return View(dadosPessoais);
            }
        }


        [Authorize]
        public ActionResult Endereco(string id)
        {
            var cliente = clienteApp.ObterPorId(id);

            var clienteEndereco = new ClienteEnderecoViewModel()
            {
                Id = cliente.Id,
                CEP = cliente.CEP,
                Endereco = cliente.Endereco,
                Numero = cliente.Numero,
                Bairro = cliente.Bairro,
                Cidade = cliente.Cidade,
                Estado = cliente.Estado                
            };

            return View(clienteEndereco);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Endereco(ClienteEnderecoViewModel clienteEndereco)
        {
            try
            {

                var cliente = clienteApp.ObterPorId(clienteEndereco.Id);

                var clienteAlterar = new Cliente()
                {
                    Id = cliente.Id,
                    Nome = cliente.Nome,
                    Email = cliente.Email,
                    Senha = cliente.Senha,
                    CPF = cliente.CPF,
                    DataNasc = cliente.DataNasc,
                    Sexo = cliente.Sexo,
                    Telefone = cliente.Telefone,
                    CEP = clienteEndereco.CEP,
                    Endereco = clienteEndereco.Endereco,
                    Numero = clienteEndereco.Numero,
                    Bairro = clienteEndereco.Bairro,
                    Cidade = clienteEndereco.Cidade,
                    Estado = clienteEndereco.Estado
                };

                clienteApp.Alterar(clienteAlterar);

                return RedirectToAction("DashboardCliente");
            }
            catch
            {
                return View(clienteEndereco);
            }
        }
    }
}

PcSantos.UI.Web/Controllers/PedidoController.cs
using PcSantos.ApplicationServices;
using PcSantos.Domain;
using PcSantos.Domain.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PcSantos.UI.Web.Controllers
{
    public class PedidoController : Controller
    {
        private IPedidoAppServices pedidoApp;
        private IProdutoAppServices produtoApp;
        private IClienteAppServices clienteApp;

        public PedidoController(IPedidoAppServices pedidoAppInstance, IProdutoAppServices produtoAppInstance, IClienteAppServices clienteAppInstance)
        {
            this.pedidoApp = pedidoAppInstance;
            this.produtoApp = produtoAppInstance;
            this.clienteApp = clienteAppInstance;
        }
        
        [Authorize]
        public ActionResult Compra(string id)
        {              
            var produto = produtoApp.ObterPorId(id);
            var pedidoCompraViewModel = new PedidoCompraViewModel()
            {
                Id = produto.Id,
                Categoria = produto.Categoria,
                Descricao = produto.Descricao,
                Valor = produto.Valor,
                FichaTecnica = produto.FichaTecnica,
                ValorTotal = produto.Valor
            };
            return View(pedidoCompraViewModel);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Compra(PedidoCompraViewModel pedidoViewModel)
        {
            var clienteId = AppHelper.ObterClienteLogado();
            var cliente = clienteApp.ObterPorId(clienteId.Id);

            var pedido = new Pedido()
            {
                Id = Guid.NewGuid().ToString(),
                Cliente = new Cliente()
                {
                    Id = cliente.Id,
                    Nome = cliente.Nome,
                    Email = cliente.Email,
                    Senha = cliente.Senha,
                    CPF = cliente.CPF,
                    DataNasc = cliente.DataNasc,
                    Sexo = cliente.Sexo,
                    Telefone = cliente.Telefone,
                    CEP = cliente.CEP,
                    Endereco = cliente.Endereco,
                    Numero = cliente.Numero,
                    Bairro = cliente.Bairro,
                    Cidade = cliente.Cidade,
                    Estado = cliente.Estado
                },
                Status = (PedidoStatus)1,
                ListaProdutos = new List<PedidoItem>()
            };

            var consultaProduto = produtoApp.ObterPorId(pedidoViewModel.Id);
                
            var produto = new Produto()
            {
                Id = consultaProduto.Id,
                Categoria = consultaProduto.Categoria,
                Descricao = consultaProduto.Descricao,
                Valor = consultaProduto.Valor,
                FichaTecnica = consultaProduto.FichaTecnica
            };


            var lista = new PedidoItem()
            {
                Id = Guid.NewGuid().ToString(),
                PedidoId = pedido.Id,
                NumeroPedido = pedido.Numero,                    
                Produto = produto,
                Quantidade = 2                
            };
            lista.Total = produto.Valor * lista.Quantidade;

            var listaPed = new List<PedidoItem>();

            listaPed.Add(lista);            
            
            foreach (var p in listaPed)
            {
                pedido.ValorTotal += p.Total;
            }

            pedido.ListaProdutos.Add(lista);            

            pedidoApp.IncluirPedido(pedido); 
            
            
            
            var consultaPedido = pedidoApp.ObterPedidoPorId(pedido.Id);

            var pedido2 = new Pedido()
            {
                Numero = consultaPedido.Numero,                
                ListaProdutos = new List<PedidoItem>()
            };

            var produto2 = new Produto()
            {
                Id = consultaProduto.Id,
                Categoria = consultaProduto.Categoria,
                Descricao = consultaProduto.Descricao,
                Valor = consultaProduto.Valor,
                FichaTecnica = consultaProduto.FichaTecnica
            };


            var lista2 = new PedidoItem()
            {
                Id = Guid.NewGuid().ToString(),
                PedidoId = pedido.Id,
                NumeroPedido = consultaPedido.Numero,
                Produto = produto2,
                Quantidade = 2                
            };
            lista2.Total = produto2.Valor * lista2.Quantidade;

            pedido2.ListaProdutos.Add(lista2);            

            pedidoApp.IncluirPedidoItem(pedido2);

            return RedirectToAction("CompraFinalizada");
            
        }

        [Authorize]
        public ActionResult CompraFinalizada()
        {
            return View();
        }

        [Authorize]
        public ActionResult Pedidos(string id)
        {
            var cliente = clienteApp.ObterPorId(id);
            var pedidosCliente = pedidoApp.ObterPedidoPorClienteId(cliente.Id);
            
                      
            var pedidos = new List<PedidoDetalhesViewModel>();  
            
            foreach(var p in pedidosCliente)
            {
                var numero = p.Numero;
                var ped = pedidoApp.ObterPedidoPorNumero(numero);

                var pedid = new Pedido()
                {
                    Numero = ped.Numero,
                    ListaProdutos = new List<PedidoItem>(),
                    ValorTotal = ped.ValorTotal,
                    Status = ped.Status
                };

                foreach (var f in ped.ListaProdutos)
                {
                    pedid.ListaProdutos.Add(new PedidoItem()
                    {
                        Produto = new Produto()
                        {
                            Categoria = f.Produto.Categoria,
                            Descricao = f.Produto.Descricao,
                            Valor = f.Produto.Valor,
                        },
                        Quantidade = f.Quantidade,
                        Total = f.Total
                    });
                }
                pedidos.Add(new PedidoDetalhesViewModel
                {
                    NumeroPedido = pedid.Numero,
                    Produtos = pedid.ListaProdutos,
                    ValorTotal = pedid.ValorTotal,
                    StatusPedido = pedid.Status
                });
            }
            return View(pedidos);
        }
    }
}

PcSantos.UI.Web/Views/Cliente/DadosPessoais.cshtml
@model PcSantos.Domain.ClienteDadosPessoaisViewModel

@{
    ViewBag.Title = "DadosPessoais";
}

<h3>Dados Pessoais</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNasc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNasc, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar", "DashboardCliente")
</div>

PcSantos.UI.Web/Views/Cliente/DashboardCliente.cshtml
@model PcSantos.Domain.Cliente

@{
    ViewBag.Title = "DashboardCliente";
}

    <h3>Minha Conta</h3>
    <br />

    <ul class="nav">
        <li class="nav-item">
            <a href='@Url.Action("DadosPessoais", "Cliente", new { id = @Model.Id })'><i class="glyphicon glyphicon-check"></i>Dados Pessoais</a>
        </li>

        <li class="nav-item">
            <a href='@Url.Action("Endereco", "Cliente", new { id = @Model.Id })'><i class="glyphicon glyphicon-check"></i>Endereço</a>
        </li>     

        <li class="nav-item">
            <a href='@Url.Action("Pedidos", "Pedido", new { id = @Model.Id })'><i class="glyphicon glyphicon-check"></i>Pedidos</a>
        </li>

    </ul>
    

PcSantos.UI.Web/Views/Cliente/Endereco.cshtml
@model PcSantos.Domain.ClienteEnderecoViewModel

@{
    ViewBag.Title = "Endereco";
}

<h3>Endereço</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CEP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar", "DashboardCliente")
</div>

PcSantos.UI.Web/Views/Cliente/Login.cshtml
@model PcSantos.Domain.ClienteLoginViewModel

@{
    ViewBag.Title = "Login";
}

<h3>Login</h3>


<form method="post">
    <div class="form-horizontal">


        <div id="mensagem">@Model.Mensagem</div>
        
        <div class="form-group">
            <label class="control-label" for="Email">Email:</label>
            <input value="@Model.Email" class="form-control" type="text" name="Email" id="Email" />
        </div>

        <div class="form-group">
            <label class="control-label" for="Senha">Senha:</label>
            <input value="@Model.Senha" class="form-control" type="password" name="Senha" id="Senha" />
        </div>

        <div class="form-group">
            <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-check"></span> Entrar</button>
        </div>

    </div>
</form>

<div>
    @Html.ActionLink("Não possui Login? Registre-se", "Registro")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PcSantos.UI.Web/Views/Cliente/Registro.cshtml
@model PcSantos.Domain.ClienteRegistroViewModel

@{
    ViewBag.Title = "Registro";
}

<h3>Registre-se</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.Senha, new { @class = "form-control" } )
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ConfirmarSenha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.ConfirmarSenha, new { @class = "form-control" } )
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataNasc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataNasc, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CEP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-save"></span> Cadastrar</button>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Já possui Login? Entre", "Login")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}